"use client";

import { api } from "@/lib/api";
import { useEffect, useState } from "react";
import { useAuthStore } from "@/lib/auth-store";
import { CheckCircle, ShieldAlert } from "lucide-react";
import { Card, CardHeader } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DataTable, type Column } from "@/components/ui/data-table";
import { TableSkeleton } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/ui/empty-state";
import { Rise } from "@/components/ui/motion";
import { useToast } from "@/components/ui/toast";

interface TakedownPolicy {
  id: number;
  case_number: string;
  target: string;
  target_type: string;
  action: string;
  reason: string;
  created_at: string;
}

export default function BankerDashboard() {
  const { token } = useAuthStore();
  const toast = useToast();
  const [policies, setPolicies] = useState<TakedownPolicy[]>([]);
  const [loading, setLoading] = useState(true);
  const [processing, setProcessing] = useState<number | null>(null);

  useEffect(() => {
    const fetchPendingPolicies = async () => {
      if (!token) return;
      try {
        const res = await fetch(api("/takedowns/pending"), {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (res.ok) {
          const data = await res.json();
          setPolicies(data);
        }
      } catch (error) {
        console.error("Failed to fetch policies", error);
      } finally {
        setLoading(false);
      }
    };
    fetchPendingPolicies();
  }, [token]);

  const approvePolicy = async (id: number) => {
    if (!token) return;
    setProcessing(id);
    try {
      const res = await fetch(api(`/takedowns/${id}/approve`), {
        method: "POST",
        headers: { Authorization: `Bearer ${token}` },
      });

      if (res.ok) {
        setPolicies((prev) => prev.filter((p) => p.id !== id));
        toast("success", "Takedown executed.");
      } else {
        toast("danger", "The takedown couldn't be approved.");
      }
    } catch (error) {
      console.error("Error approving policy", error);
      toast("danger", "The takedown couldn't be approved.");
    } finally {
      setProcessing(null);
    }
  };

  const columns: Column<TakedownPolicy>[] = [
    {
      key: "target",
      header: "Target",
      mobile: "title",
      render: (p) => <span className="font-medium text-ink break-all tabular">{p.target}</span>,
    },
    {
      key: "case_number",
      header: "Case",
      render: (p) => <span className="tabular text-ink-2">{p.case_number}</span>,
    },
    {
      key: "target_type",
      header: "Type",
      render: (p) => <Badge className="uppercase">{p.target_type}</Badge>,
    },
    {
      key: "action",
      header: "Requested action",
      render: (p) => (
        <span className="capitalize text-ink">{p.action.replace(/_/g, " ")}</span>
      ),
    },
    {
      key: "reason",
      header: "Reason",
      mobile: "meta",
      render: (p) => (
        <span className="text-ink-2 block max-w-xs truncate" title={p.reason}>
          {p.reason}
        </span>
      ),
    },
    {
      key: "approve",
      header: "",
      align: "right",
      mobile: "trailing",
      render: (p) => (
        <Button
          variant="danger"
          size="sm"
          loading={processing === p.id}
          onClick={() => approvePolicy(p.id)}
        >
          Execute takedown
        </Button>
      ),
    },
  ];

  return (
    <div className="space-y-6 pt-2">
      <Rise>
        <PageHeader
          title="Nodal desk"
          sub="Takedown requests generated by the AI core, awaiting your sign-off."
        />
      </Rise>

      <Rise index={1}>
        <Card>
          <CardHeader
            title="Pending takedowns"
            sub={loading ? undefined : `${policies.length} awaiting approval`}
            action={
              !loading && policies.length > 0 ? (
                <Badge tone="warning">
                  <ShieldAlert className="w-3 h-3" />
                  Action needed
                </Badge>
              ) : undefined
            }
          />
          {loading ? (
            <TableSkeleton rows={4} />
          ) : policies.length === 0 ? (
            <EmptyState
              icon={CheckCircle}
              title="All clear"
              body="No takedown requests are waiting on you right now."
            />
          ) : (
            <DataTable columns={columns} rows={policies} rowKey={(p) => p.id} />
          )}
        </Card>
      </Rise>
    </div>
  );
}
