"""Add admin_reply to support_tickets

Revision ID: 305d215ea8ab
Revises: c70db44322db
Create Date: 2026-07-13 09:03:33.724584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305d215ea8ab'
down_revision: Union[str, Sequence[str], None] = 'c70db44322db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('admin_reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'admin_reply')
    # ### end Alembic commands ###
