"""Add OTP and lockout fields to user

Revision ID: 48db3f7591cd
Revises: c4c61f939081
Create Date: 2026-07-05 23:30:28.088210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48db3f7591cd'
down_revision: Union[str, Sequence[str], None] = 'c4c61f939081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_failed_attempts', sa.Integer(), server_default='0', nullable=True))
    op.add_column('users', sa.Column('otp_lockout_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('users', sa.Column('otp_locked_until', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'otp_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'otp_locked_until')
    op.drop_column('users', 'otp_lockout_count')
    op.drop_column('users', 'otp_failed_attempts')
    # ### end Alembic commands ###
