"""Add chat_session_ref and history to SupportTicket

Revision ID: 60730b70fe7c
Revises: 305d215ea8ab
Create Date: 2026-07-13 16:40:00.423318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60730b70fe7c'
down_revision: Union[str, Sequence[str], None] = '305d215ea8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('chat_session_ref', sa.String(), nullable=True))
    op.add_column('support_tickets', sa.Column('history', sa.JSON(), nullable=True))
    op.drop_column('support_tickets', 'admin_reply')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('admin_reply', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('support_tickets', 'history')
    op.drop_column('support_tickets', 'chat_session_ref')
    # ### end Alembic commands ###
