"""add_lat_long_to_case

Revision ID: 61ef2004dc9b
Revises: 5df1e78a208c
Create Date: 2026-06-30 02:00:38.361290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ef2004dc9b'
down_revision: Union[str, Sequence[str], None] = '5df1e78a208c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('cases', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'longitude')
    op.drop_column('cases', 'latitude')
    # ### end Alembic commands ###
