"""add_hashed_password

Revision ID: 786f458c69ac
Revises: 373d914ec431
Create Date: 2026-07-04 17:58:12.718220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '786f458c69ac'
down_revision: Union[str, Sequence[str], None] = '373d914ec431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('attack_dna', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cases', sa.Column('timeline_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('cases', 'timeline_events')
    op.drop_column('cases', 'attack_dna')
    # ### end Alembic commands ###
