"""Actually add scam_patterns table

Revision ID: c4c61f939081
Revises: da92045f4124
Create Date: 2026-07-05 20:25:37.638424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c61f939081'
down_revision: Union[str, Sequence[str], None] = 'cdb4943c29dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scam_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scam_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('raw_text_example', sa.Text(), nullable=True),
    sa.Column('modus_operandi', sa.Text(), nullable=True),
    sa.Column('indicators_of_compromise', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scam_patterns_id'), 'scam_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_scam_patterns_scam_type'), 'scam_patterns', ['scam_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scam_patterns_scam_type'), table_name='scam_patterns')
    op.drop_index(op.f('ix_scam_patterns_id'), table_name='scam_patterns')
    op.drop_table('scam_patterns')
    # ### end Alembic commands ###
