"""Add assigned_phone to case

Revision ID: c53438b407e5
Revises: cad8cd143536
Create Date: 2026-07-09 01:11:13.859113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53438b407e5'
down_revision: Union[str, Sequence[str], None] = 'cad8cd143536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('assigned_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'assigned_phone')
    # ### end Alembic commands ###
