"""Add pgvector and knowledge models

Revision ID: c542794eee4a
Revises: 60730b70fe7c
Create Date: 2026-07-13 18:09:31.975351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'c542794eee4a'
down_revision: Union[str, Sequence[str], None] = '60730b70fe7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    
    op.create_table('fraud_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mistake_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_scam_text', sa.Text(), nullable=False),
    sa.Column('ai_original_decision', sa.Text(), nullable=False),
    sa.Column('human_correction', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_guidelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('support_tickets', 'history',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_tickets', 'history',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_table('regulatory_guidelines')
    op.drop_table('mistake_corrections')
    op.drop_table('fraud_patterns')
    
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
