"""Add help_messages table

Revision ID: c70db44322db
Revises: d50556e5e56b
Create Date: 2026-07-11 05:30:16.131164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c70db44322db'
down_revision: Union[str, Sequence[str], None] = 'd50556e5e56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_messages_id'), 'help_messages', ['id'], unique=False)
    op.create_index(op.f('ix_help_messages_session_id'), 'help_messages', ['session_id'], unique=False)
    op.add_column('threat_patterns', sa.Column('pattern_signature', sa.String(), nullable=False))
    op.add_column('threat_patterns', sa.Column('severity_score', sa.Float(), nullable=False))
    op.alter_column('threat_patterns', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_threat_patterns_pattern_signature'), 'threat_patterns', ['pattern_signature'], unique=True)
    op.drop_column('threat_patterns', 'category')
    op.drop_column('threat_patterns', 'name')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('threat_patterns', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('threat_patterns', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_threat_patterns_pattern_signature'), table_name='threat_patterns')
    op.alter_column('threat_patterns', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('threat_patterns', 'severity_score')
    op.drop_column('threat_patterns', 'pattern_signature')
    op.drop_index(op.f('ix_help_messages_session_id'), table_name='help_messages')
    op.drop_index(op.f('ix_help_messages_id'), table_name='help_messages')
    op.drop_table('help_messages')
    # ### end Alembic commands ###
