"""Add support tickets and encrypted fields

Revision ID: cad8cd143536
Revises: 48db3f7591cd
Create Date: 2026-07-09 01:07:11.110444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'cad8cd143536'
down_revision: Union[str, Sequence[str], None] = '48db3f7591cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('victim_id', sa.UUID(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['victim_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.add_column('cases', sa.Column('victim_phone', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True))
    op.add_column('cases', sa.Column('victim_address', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True))
    op.add_column('users', sa.Column('station_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'station_phone_number')
    op.drop_column('cases', 'victim_address')
    op.drop_column('cases', 'victim_phone')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
