"""Add file_hash_sha256 to evidence

Revision ID: cdb4943c29dd
Revises: 786f458c69ac
Create Date: 2026-07-05 17:19:56.221580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb4943c29dd'
down_revision: Union[str, Sequence[str], None] = '786f458c69ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('file_hash_sha256', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_evidence_file_hash_sha256'), 'evidence', ['file_hash_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_file_hash_sha256'), table_name='evidence')
    op.drop_column('evidence', 'file_hash_sha256')
    # ### end Alembic commands ###
