"""Update schema

Revision ID: d50556e5e56b
Revises: c53438b407e5
Create Date: 2026-07-09 01:38:36.627280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50556e5e56b'
down_revision: Union[str, Sequence[str], None] = 'c53438b407e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('ticket_number', sa.String(), nullable=False))
    op.add_column('support_tickets', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('support_tickets', sa.Column('subject', sa.String(), nullable=False))
    op.add_column('support_tickets', sa.Column('message', sa.Text(), nullable=False))
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    op.drop_constraint(op.f('support_tickets_victim_id_fkey'), 'support_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'support_tickets', 'users', ['user_id'], ['id'])
    op.drop_column('support_tickets', 'victim_id')
    op.drop_column('support_tickets', 'issue_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('issue_description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('support_tickets', sa.Column('victim_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('support_tickets_victim_id_fkey'), 'support_tickets', 'users', ['victim_id'], ['id'])
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.drop_column('support_tickets', 'message')
    op.drop_column('support_tickets', 'subject')
    op.drop_column('support_tickets', 'user_id')
    op.drop_column('support_tickets', 'ticket_number')
    # ### end Alembic commands ###
