"""add_ai_audit_logs_table

Revision ID: ec8e91f05a89
Revises: c542794eee4a
Create Date: 2026-07-16 01:39:41.686893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8e91f05a89'
down_revision: Union[str, Sequence[str], None] = 'c542794eee4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chain_of_custody_evidence_id'), 'chain_of_custody', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_chain_of_custody_id'), 'chain_of_custody', ['id'], unique=False)
    op.create_index(op.f('ix_chain_of_custody_timestamp'), 'chain_of_custody', ['timestamp'], unique=False)
    op.drop_constraint(op.f('chain_of_custody_evidence_id_fkey'), 'chain_of_custody', type_='foreignkey')
    op.create_foreign_key(None, 'chain_of_custody', 'evidence', ['evidence_id'], ['id'])
    op.alter_column('evidence', 'case_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('evidence', 'integrity_status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'VERIFIED'::character varying"))
    op.create_index(op.f('ix_evidence_evidence_owner'), 'evidence', ['evidence_owner'], unique=False)
    op.create_index(op.f('ix_evidence_sha256'), 'evidence', ['sha256'], unique=False)
    op.create_index(op.f('ix_help_messages_user_id'), 'help_messages', ['user_id'], unique=False)
    op.alter_column('support_tickets', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_tickets', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_help_messages_user_id'), table_name='help_messages')
    op.drop_index(op.f('ix_evidence_sha256'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_owner'), table_name='evidence')
    op.alter_column('evidence', 'integrity_status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'VERIFIED'::character varying"))
    op.alter_column('evidence', 'case_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'chain_of_custody', type_='foreignkey')
    op.create_foreign_key(op.f('chain_of_custody_evidence_id_fkey'), 'chain_of_custody', 'evidence', ['evidence_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chain_of_custody_timestamp'), table_name='chain_of_custody')
    op.drop_index(op.f('ix_chain_of_custody_id'), table_name='chain_of_custody')
    op.drop_index(op.f('ix_chain_of_custody_evidence_id'), table_name='chain_of_custody')
    # ### end Alembic commands ###
